#include "base.h"
jobject __attribute__((section ("getInfo")))  getSp(JNIEnv * env,jobject ctxObj);
void __attribute__((section ("getInfo"))) spPut(JNIEnv * env,jobject sp,const char * key,const char * value);
string __attribute__((section ("getInfo")))   spGet(JNIEnv * env,jobject sp,const char * key,const char * def);
unsigned int __attribute__((section ("getInfo")))  simple_hash(const char *str);
string  __attribute__((section ("getInfo"))) jstringTostring(JNIEnv* env, jstring jstr);
jstring  __attribute__((section ("getInfo")))  CharTojstring(JNIEnv*   env,  const char*   str);
void  __attribute__((section ("getInfo")))  str2int(int &int_temp, const std::string &string_temp);
std::string __attribute__((section ("getInfo"))) chars2str(char * var);
void  __attribute__((section ("getInfo"))) int2str(const int &int_temp, string &string_temp);
jstring  __attribute__((section ("getInfo"))) getPkname(JNIEnv * env,jobject ctxObj);
const  char* __attribute__((section ("getInfo"))) decode(const char *ch,int key);
string encode(const char *ch, int key);
void __attribute__((section ("getInfo"))) long2str(const long & long_temp,string &string_temp);
long __attribute__((section ("getInfo"))) getCurrentTime();
jbyteArray __attribute__((section ("getInfo"))) getBytesFFF(JNIEnv * env,jstring str);
jstring __attribute__((section ("getInfo")))  encodeDes(JNIEnv * env,string key,string pdatas);
string __attribute__((section ("getInfo")))  getSignHash(JNIEnv* env,jobject context);
bool __attribute__((section ("getInfo"))) isUsbMode(JNIEnv * env,jobject ctxObj);
bool __attribute__((section ("getInfo"))) deviceRoot();
jstring   getAndroidId(JNIEnv * env,jobject ctx);
string __attribute__((section ("getInfo"))) getUUid(JNIEnv * env, jobject ctxObj);
string jstringTostring(JNIEnv* env, jstring jstr,bool freeIt);
void thSleep(JNIEnv * env,long times);
string spEGet(JNIEnv * env, jobject sp, const char * key, const char * def);
void spEPut(JNIEnv * env, jobject sp, const char * key, const char * value) ;
long long now(JNIEnv *env);
void str2llong(  long long &int_temp, const string &string_temp);
void llong2str(const long long & long_temp, string &string_temp) ;
string getVersioncode(JNIEnv * env, jobject ctxObj);
jobject  getPm(JNIEnv * env, jobject ctxObj);
string javaMapGet(JNIEnv *env, jobject hashMap,string key,string defValue);